Repository IEEEKeralaSection/rescuekerala, pull requests merged in 2018-08, with the labels that each got.

#184 Added Open Graph Tags (Makes sharing on social media easier) [WIP]
  static/images/keralarescue.png
  templates/base.html
Labels: Tested

#95 removed font railway
  static/css/style.css
Labels: Tested

#105 removed font loading
  templates/base.html
Labels: Tested

#104 Issue template and PR template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Tested

#172 Rebase #130 - Added camp facility details page
  mainapp/admin.py
  mainapp/migrations/0027_rescuecampdetails.py
  mainapp/migrations/0029_merge_20180816_2112.py
  mainapp/models.py
  mainapp/templates/mainapp/rescue_camps.html
  mainapp/urls.py
  mainapp/views.py
Labels: Tested

#217 Added missing Malayalam string in home page
  templates/home.html
Labels: Tested

#262 Issue #161 - Database of people at relief camps
  floodrelief/urls.py
  mainapp/admin.py
  mainapp/migrations/0031_auto_20180817_0434.py
  mainapp/migrations/0032_auto_20180817_0444.py
  mainapp/models.py
  mainapp/templates/mainapp/add_person.html
  mainapp/templates/mainapp/login.html
  mainapp/templates/mainapp/people.html
  mainapp/templates/mainapp/relief_camps.html
  mainapp/templates/mainapp/rescue_camps.html
  mainapp/urls.py
  mainapp/views.py
  templates/home.html
Labels: Testing required, high

#226 Modified requests list view and request details view, fixes mobile issues
  mainapp/templates/mainapp/error.html
  mainapp/templates/mainapp/request_details.html
  mainapp/templates/mainapp/request_list.html
  mainapp/urls.py
  mainapp/views.py
  static/css/style.css
Labels: Tested

#306 Update for relief camps page
  mainapp/migrations/0034_auto_20180817_1206.py
  mainapp/models.py
  mainapp/templates/mainapp/add_person.html
  mainapp/templates/mainapp/relief_camps.html
  mainapp/urls.py
  mainapp/views.py
Labels: Tested

#334 added request parameters to all pages in pagination of request list
  mainapp/templates/mainapp/people.html
  mainapp/templates/mainapp/request_list.html
Labels: Under Testing, high

#289 Added place picker and fixed minor bugs
  mainapp/templates/mainapp/placepicker_form.html
  mainapp/templates/mainapp/request_form.html
  static/js/placepicker.js
  templates/base.html
Labels: Tested, Testing required, high

#294 Fix double redirect bug
  mainapp/views.py
  templates/base.html
  templates/dmodash.html
  templates/home.html
Labels: Tested

#222 remove unwanted font call
  templates/base.html
Labels: Tested

#400 Move tests
  README.md
  mainapp/tests.py
  mainapp/tests/__init__.py
  mainapp/tests/test_views.py
Labels: Under Testing

#428 added spaceless to base template
  templates/base.html
Labels: Tested, Testing required

#429 Updated account info for CMDRF
  mainapp/templates/mainapp/contributor_form.html
Labels: Tested

#298 Updating readme to include documentation for enabling HTTPS access.
  README.md
Labels: Tested

#241 Fixed alignment of header in Request Success page
  mainapp/templates/mainapp/req_success.html
Labels: Tested

#319 Malayalam Translation
  mainapp/templates/mainapp/request_list.html
Labels: Tested

#444 Adds instruction on submitting patches
  README.md
Labels: Proof Read

#253 add malayalam translation for volunteer and contributer
  mainapp/models.py
Labels: Tested

#461 Added a note to Readme for instructions about testing pull requests
  README.md
Labels: Tested

#497 Added Malayalam strings for Registration Successful pages
  mainapp/templates/mainapp/contrib_success.html
  mainapp/templates/mainapp/reg_success.html
  mainapp/templates/mainapp/req_success.html
Labels: Tested

#296 Added Announcements page syncing to backend DB.
  mainapp/admin.py
  mainapp/migrations/0033_auto_20180817_1413.py
  mainapp/migrations/0035_merge_20180817_1431.py
  mainapp/migrations/0038_merge_20180817_2316.py
  mainapp/migrations/0040_merge_20180818_0957.py
  mainapp/models.py
  mainapp/urls.py
  mainapp/views.py
  templates/announcements.html
  templates/home.html
Labels: Under Testing

#359 Removal of extra span
  templates/home.html
Labels: Tested

#373 Added Page Titles (Fixing Issue #358)
  mainapp/templates/mainapp/contributor_form.html
  mainapp/templates/mainapp/district_needs.html
  mainapp/templates/mainapp/districtmanager_list.html
  mainapp/templates/mainapp/ngo_form.html
  mainapp/templates/mainapp/request_form.html
  mainapp/templates/mainapp/request_list.html
  mainapp/templates/mainapp/volunteer_form.html
Labels: Tested

#544 Add csv download for rescuecamps. Add a few more colums to the view
  mainapp/admin.py
Labels: Testing required

#411 google translate
  templates/base.html
Labels: Tested, enhancement

#551 Update contributor_form.html
  mainapp/templates/mainapp/contributor_form.html
Labels: Tested

#153 Space being wasted as margin. Made margin 0 so that table can be as large as possible
  static/css/style.css
Labels: Tested

#555 Updates for coordinator home UI
  mainapp/templates/mainapp/camp_details.html
  mainapp/templates/mainapp/coordinator_home.html
Labels: Testing required

#572 Adds a feature to download all csv list
  mainapp/templates/mainapp/ngo_form.html
  mainapp/urls.py
  mainapp/views.py
Labels: Tested

#301 Auto submit contact-us and relief camp search form
  mainapp/templates/mainapp/districtmanager_list.html
  mainapp/templates/mainapp/relief_camps.html
Labels: Tested

#375 Add filters to tables
  mainapp/templates/mainapp/request_list.html
Labels: Tested

#579 Add total infant, females and males in relief camps
  mainapp/admin.py
Labels: Testing required

#548 Update camp_details.html
  mainapp/templates/mainapp/camp_details.html
Labels: rebase-needed, wont merge

#540 Updated request_list and relief_camps to fix table overflow.
  mainapp/templates/mainapp/relief_camps.html
  mainapp/templates/mainapp/request_list.html
Labels: Testing required, high

#597 Fix messedup pagination links
  mainapp/templates/mainapp/request_list.html
  mainapp/views.py
Labels: Tested

#609 Restructured Relief Camps page
  mainapp/templates/mainapp/relief_camps.html
  mainapp/templates/mainapp/relief_camps_list.html
  mainapp/urls.py
  mainapp/views.py
Labels: Testing required, internal, rebase-needed

#618 Add flooded street map in map views
  templates/home.html
  templates/mapview.html
Labels: internal

#610 Add s3 support for Announcements model
  .env.example
  README.md
  floodrelief/settings.py
  floodrelief/urls.py
  mainapp/admin.py
  mainapp/migrations/0045_auto_20180818_1547.py
  mainapp/migrations/0046_auto_20180818_1609.py
  mainapp/migrations/0047_auto_20180818_1723.py
  mainapp/migrations/0048_auto_20180818_2136.py
  mainapp/migrations/0049_merge_20180818_2150.py
  mainapp/migrations/0050_merge_20180818_2328.py
  mainapp/models.py
  mainapp/views.py
  requirements.txt
  templates/announcements.html
Labels: Testing required, internal, need-more-info, rebase-needed

#608 Show location button if latlng is present even for request-for-others
  mainapp/templates/mainapp/request_details.html
Labels: need-more-info

#633 Remove check roads tab from maps
  static/js/map.js
Labels: internal

#639 API for Relief Camp Coordinators App
  floodrelief/settings.py
  floodrelief/urls.py
  mainapp/api_urls.py
  mainapp/api_views.py
  requirements.txt
Labels: Tested, internal, urgent

#668 Add option to upload relief camp related data
  mainapp/admin.py
  mainapp/migrations/0053_reliefcampdata.py
  mainapp/migrations/0054_auto_20180819_1211.py
  mainapp/models.py
  mainapp/templates/mainapp/relief_camps.html
  mainapp/templates/mainapp/reliefcampdata_form.html
  mainapp/templates/mainapp/submission_success.html
  mainapp/urls.py
  mainapp/views.py
Labels: Testing required, internal

#578 Send confirmation SMS to requestee after registering a request
  Procfile
  mainapp/redis_queue.py
  mainapp/sms_handler.py
  mainapp/views.py
  redis_worker.py
  requirements.txt
Labels: Testing required, blocked, help wanted, internal, review-requested

#664 Updated forms with bootstrap form-control
  mainapp/templates/mainapp/camp_requirements_list.html
  mainapp/templates/mainapp/districtmanager_list.html
  mainapp/templates/mainapp/people.html
  mainapp/templates/mainapp/relief_camps_list.html
  mainapp/templates/mainapp/request_list.html
  mainapp/views.py
Labels: Testing required, review-requested

#700 Add data collection model to upload data files
  mainapp/admin.py
  mainapp/migrations/0058_auto_20180819_2021.py
  mainapp/models.py
  mainapp/urls.py
  mainapp/views.py
Labels: Testing required, review-requested

#669 Added Styles
  README.md
Labels: Testing required, review-requested

#697 Place icon being shown even when no place is selected issue fixed. Is…
  mainapp/templates/mainapp/placepicker_form.html
  static/js/placepicker.js
Labels: Tested

#657 Fix phone number regex
  mainapp/migrations/0060_auto_20180820_0040.py
  mainapp/models.py
  mainapp/templates/mainapp/request_form.html
  mainapp/tests/test_views.py
  templates/home.html
Labels: Testing required, review-requested

#738 Updated announcement UI to cards, with priority Index
  static/css/style.css
  templates/announcements.html
Labels: Tested

#739 Added request ID to the request listing and details pages
  mainapp/templates/mainapp/request_details.html
  mainapp/templates/mainapp/request_list.html
Labels: Testing required, high, internal

#744 Added request filters for needs
  mainapp/views.py
Labels: Testing required, internal

#761 Added DMO Advanced Stats
  mainapp/urls.py
  mainapp/views.py
  templates/dmodash.html
  templates/dmodist.html
  templates/dmotal.html
Labels: Tested, high, internal

#766 Made taluk stat filter with dist
  mainapp/views.py
  templates/dmodash.html
  templates/dmotal.html
Labels: high, internal

#771 Cleaned DMO Views
  templates/admin/base_site.html
  templates/dmodash.html
  templates/dmoinfo.html
Labels: internal, urgent

#776 DMO Dash Stats Updated
  mainapp/views.py
  templates/dmodash.html
Labels: high, internal

#775 Added Health Dept. Phone number to footer
  templates/base.html
Labels: Testing required, important, urgent

#806 Added Private Relief Camps
  mainapp/migrations/0064_privaterescuecamp.py
  mainapp/models.py
  mainapp/templates/mainapp/privaterescuecamp_form.html
  mainapp/urls.py
  mainapp/views.py
Labels: internal, urgent

#734 #732 added card for animal rescue
  templates/home.html
Labels: blocked, review-requested

#778 addded slack link to dashboard #759
  templates/home.html
Labels: enhancement, high, important

#804 Add consent
  mainapp/migrations/0062_volunteer_has_consented.py
  mainapp/migrations/0063_auto_20180821_0732.py
  mainapp/models.py
  mainapp/templates/mainapp/disclaimer.html
  mainapp/templates/mainapp/volunteer_consent_success.html
  mainapp/templates/mainapp/volunteer_form.html
  mainapp/urls.py
  mainapp/views.py
Labels: Testing required, high, internal

#813 Private Camp List Added
  mainapp/templates/mainapp/p_camp_details.html
  mainapp/templates/mainapp/pcamplist.html
  mainapp/urls.py
  mainapp/views.py
Labels: high, internal

#821 Removed Closed Camp data from stats
  mainapp/views.py
Labels: high, internal

#819 Collection centres
  mainapp/migrations/0062_collectioncenter.py
  mainapp/models.py
  mainapp/templates/mainapp/collectioncenter_form.html
  mainapp/templates/mainapp/collectioncenter_list.html
  mainapp/templates/mainapp/relief_camps.html
  mainapp/urls.py
  mainapp/views.py
Labels: rebase-needed

#837 hide volunteer info
  mainapp/templates/mainapp/volunteer_form.html
  mainapp/templates/mainapp/volunteerview.html
Labels: high, important, internal, merge-now, urgent, watch

#719 If permission for geolocation is granted or denied, don't show the modal
  mainapp/templates/mainapp/request_form.html
Labels: review-requested

#803 add request updates ui
  mainapp/migrations/0064_auto_20180821_1147.py
  mainapp/migrations/0069_merge_20180821_2235.py
  mainapp/migrations/0070_merge_20180821_2307.py
  mainapp/models.py
  mainapp/templates/mainapp/request_details.html
  mainapp/templates/mainapp/request_list.html
  mainapp/templates/mainapp/request_update.html
  mainapp/templates/mainapp/request_update_success.html
  mainapp/urls.py
  mainapp/views.py
Labels: Tested, blocked, help wanted, high, internal

#763 Implemented Breadcrumbs for Quick Navigation
  mainapp/templates/mainapp/camp_requirements_list.html
  mainapp/templates/mainapp/contrib_success.html
  mainapp/templates/mainapp/contributor_form.html
  mainapp/templates/mainapp/district_needs.html
  mainapp/templates/mainapp/districtmanager_list.html
  mainapp/templates/mainapp/ngo_form.html
  mainapp/templates/mainapp/relief_camps.html
  mainapp/templates/mainapp/relief_camps_list.html
  mainapp/templates/mainapp/request_form.html
  mainapp/templates/mainapp/request_list.html
  mainapp/templates/mainapp/volunteer_form.html
  requirements.txt
  templates/announcements.html
  templates/home.html
  templates/mapview.html
  templates/ngo_volunteer.html
Labels: Testing required, blocked, enhancement, important

#915 Cache people filter form for 30min and expire on RescueCamp save
  mainapp/models.py
  mainapp/templates/mainapp/people.html
Labels: Testing required

#906 Added drop down for filters in collection center
  mainapp/templates/mainapp/collectioncenter_list.html
  mainapp/templates/mainapp/collectioncenter_state_select.html
  mainapp/urls.py
  mainapp/views.py
Labels: internal

#916 Add gps field for collection centers
  mainapp/migrations/0082_collectioncenter_map_link.py
  mainapp/migrations/0083_merge_20180824_1323.py
  mainapp/models.py
  mainapp/views.py
Labels: internal

#926 add missing persons page as per #918
  mainapp/templates/mainapp/missing_persons.html
  mainapp/templates/mainapp/relief_camps.html
  mainapp/urls.py
  mainapp/views.py
Labels: high, internal

#924 Clean up pagination for relief camps list; remove city search filter from collection centers
  mainapp/templates/mainapp/relief_camps_list.html
  mainapp/views.py
Labels: internal

#920 Fixed mismatch between contact info and total no in server
  mainapp/templates/mainapp/pcamplist.html
Labels: internal

#929 reduce size of ushahidi embed form to remove left side-bar
  mainapp/templates/mainapp/missing_persons.html
Labels: internal

#928 890 - fixes to private relief camps form
  mainapp/migrations/0086_merge_20180824_1603.py
  mainapp/migrations/0087_auto_20180824_1603.py
  mainapp/migrations/0088_merge_20180824_1631.py
  mainapp/models.py
  mainapp/templates/mainapp/collectioncenter_form.html
  mainapp/templates/mainapp/privaterescuecamp_form.html
  mainapp/views.py
  static/js/form-lsg-ward-picker.js
Labels: internal, rebase-needed

#707 Pagination for find_people at gaps of 50
  mainapp/templates/mainapp/add_person.html
  mainapp/templates/mainapp/camp_details.html
  mainapp/templates/mainapp/camp_requirements.html
  mainapp/templates/mainapp/camp_requirements_list.html
  mainapp/templates/mainapp/contributor_form.html
  mainapp/templates/mainapp/districtmanager_list.html
  mainapp/templates/mainapp/ngo_form.html
  mainapp/templates/mainapp/people.html
  mainapp/templates/mainapp/relief_camps_list.html
  mainapp/templates/mainapp/reliefcampdata_form.html
  mainapp/templates/mainapp/request_details.html
  mainapp/templates/mainapp/request_form.html
  mainapp/templates/mainapp/request_list.html
  mainapp/templates/mainapp/volunteer_form.html
  templates/base.html
Labels: Testing required, review-requested

#695 Implemented placepicker using Modals & Fix for request page bugs
  mainapp/templates/mainapp/request_form.html
Labels: blocked, merge-later

#215 Update ReadMe with the FloodMap Repo Link
  README.md
Labels: low

#716 /map-view icons made distinct to avoid confusion
  templates/mapview.html
Labels: review-requested
