Repository IEEEKeralaSection/rescuekerala, pull requests merged in 2019-08, with the labels that each got.

#1015 Added state control room number. Changes in text.
  templates/home.html
Labels: merge-now

#1013 Update volunteerview.html #1009
  mainapp/templates/mainapp/volunteerview.html
Labels: merge-now

#1018 Urlize the links in announcements
  templates/announcements.html
Labels: Testing required, blocked, important, urgent

#1022 #1017 : Adding visible announcements button for easy visibility
  mainapp/admin.py
  mainapp/migrations/0096_auto_20190810_0301.py
  mainapp/migrations/0097_auto_20190810_0339.py
  mainapp/models.py
  mainapp/templatetags/tag_lib.py
  mainapp/urls.py
  mainapp/views.py
  templates/announcements.html
  templates/home.html
Labels: Testing required, important

#1076 Added Search/Filter to all Admin Categories
  mainapp/admin.py
Labels: important

#1062 [1061] Dynamic Meta Description for Sub Pages
  templates/announcements.html
  templates/base.html
Labels: Testing required
